# Generated by Django 5.1.2 on 2024-10-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0003_alter_station_latitude_alter_station_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traintype",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AddConstraint(
            model_name="journey",
            constraint=models.UniqueConstraint(
                fields=("departure_time", "arrival_time", "route"),
                name="unique_journey_constraint",
            ),
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.UniqueConstraint(
                fields=("source", "destination", "distance"),
                name="unique_route_constraint",
            ),
        ),
        migrations.AddConstraint(
            model_name="station",
            constraint=models.UniqueConstraint(
                fields=("name", "latitude", "longitude"),
                name="unique_station_constraint",
            ),
        ),
        migrations.AddConstraint(
            model_name="train",
            constraint=models.UniqueConstraint(
                fields=("name", "train_type"), name="unique_train_constraint"
            ),
        ),
    ]
