# Generated by Django 5.1.2 on 2024-10-13 21:37

import station.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0004_alter_traintype_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(null=True, upload_to=station.utils.image_file_path),
        ),
    ]
